/** Semantic colours keep every workflow and portal in the same light/dark system. */
const colour = (name) => `rgb(var(--${name}) / <alpha-value>)`
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: { extend: { colors: {
    'canvas': colour('canvas'),
    'surface': colour('surface'),
    'subtle': colour('subtle'),
    'elevated': colour('elevated'),
    'ink': colour('ink'),
    'muted': colour('muted'),
    'faint': colour('faint'),
    'line': colour('line'),
    'line-strong': colour('line-strong'),
    'strong': colour('strong'),
    'on-strong': colour('on-strong'),
    'brand': colour('brand'),
    'brand-hover': colour('brand-hover'),
    'accent': colour('accent'),
    'brand-soft': colour('brand-soft'),
    'brand-line': colour('brand-line'),
    'success': colour('success'),
    'success-soft': colour('success-soft'),
    'success-line': colour('success-line'),
    'warning': colour('warning'),
    'warning-soft': colour('warning-soft'),
    'warning-line': colour('warning-line'),
    'danger': colour('danger'),
    'danger-soft': colour('danger-soft'),
    'danger-line': colour('danger-line'),
    'info': colour('info'),
    'info-soft': colour('info-soft'),
    'info-line': colour('info-line'),
    'violet': colour('violet'),
    'violet-soft': colour('violet-soft'),
    'violet-line': colour('violet-line'),
  }, fontFamily: { sans: ['Manrope', 'Avenir Next', 'Segoe UI', 'sans-serif'] } } },
  plugins: [],
}
