import type { ChangeEntry, ManagedComponent } from '../../types'
import ChangeReadiness from './ChangeReadiness'
import type { ReactNode } from 'react'
import { formatDateTime } from '../../utils/dateFormat'
const label = (value: string) => value.replace(/_/g, ' ')
function Value({ title, value }: { title: string; value?: string | null }) { return <div className="min-w-0"><dt className="text-xs font-medium text-muted">{title}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm">{value || 'Not recorded'}</dd></div> }
const date = (value?: string | null) => value ? formatDateTime(value) : undefined
export default function ChangeRecordSummary({ change, components, compact = false, prerequisiteAction, actions, readinessExpected = true }: { change: ChangeEntry; components: ManagedComponent[]; compact?: boolean; readinessExpected?: boolean; actions?: ReactNode; prerequisiteAction?: (code: string) => { label: string; onClick: () => void } | undefined }) {
  const evidence = change.compliance
  const impact: Array<[string,string|null|undefined]> = [['Effect',change.evaluation_effect],['Risk',change.evaluation_risk],['Regulatory impact',change.evaluation_regulatory_impact],['CIAA impact',change.evaluation_ciaa_impact],['Complexity',change.complexity_classification],['Resources',change.resource_assessment],['Scheduling assessment',change.scheduling_assessment],['Affected documentation',change.affected_documentation || change.affected_docs_summary],['Internal approval',change.approval_decision],['Approved by / at',change.approved_by ? `${change.approved_by} · ${date(change.approved_at)}` : null],['Rejection',change.rejection_reason],['Implementation',change.implementation_notes],['Implemented by / at',change.implemented_by ? `${change.implemented_by} · ${date(change.implemented_at)}` : null],['Actual start / end',change.implemented_start_at ? `${date(change.implemented_start_at)} · ${date(change.implemented_end_at)}` : null],['Verification',change.verification_notes],['Verified by / at',change.verified_by ? `${change.verified_by} · ${date(change.verified_at)}` : null]]
  return <section aria-label="Change record" className="space-y-4">
    {!compact && <ChangeReadiness readinessExpected={readinessExpected} change={change} prerequisiteAction={prerequisiteAction} actions={actions} />}
    <dl className="grid gap-4 sm:grid-cols-2"><Value title="Description" value={change.description} /><Value title="Reason for change" value={change.justification} /><Value title="Proposed by" value={change.proposed_by_name_snapshot || change.proposed_by} /><Value title="Category" value={change.category} /><Value title="Planned start" value={date(change.planned_start_at)} /><Value title="Planned end" value={date(change.planned_end_at)} /></dl>
    <div id={compact ? undefined : "change-component-scope"}><h4 className="text-sm font-semibold">Component and version scope</h4>{change.components.length ? <ul className="mt-2 divide-y divide-line">{change.components.map(item => { const component = components.find(c => c.id === item.component_id); const snapshot = item.frozen_snapshot; return <li key={item.component_id} className="py-2 text-sm"><p className="font-medium">{snapshot?.component_uid || component?.component_uid || item.component_id} · {label(snapshot?.regulatory_scope || component?.regulatory_scope || 'unknown scope')} · relevance {snapshot?.classification_code || component?.classification_code || '?'}</p><p className="text-muted">Proposed from {item.version_at_proposal || 'not recorded'} → planned {item.planned_version || 'not recorded'}{item.implemented_version ? ` → implemented ${item.implemented_version}` : ''}</p>{item.baseline_id && <p className="break-all text-xs text-muted">Certified baseline: {item.baseline_id}</p>}{item.baseline_scope_assessment && <p className="whitespace-pre-wrap text-sm">Baseline scope assessment: {item.baseline_scope_assessment}</p>}{(item.planned_checksum_hash || item.implemented_checksum_hash) && <p className="break-all text-xs text-muted">Planned checksum: {item.planned_checksum_hash || 'not recorded'} · Actual checksum: {item.implemented_checksum_hash || 'not recorded'}</p>}</li> })}</ul> : <p className="mt-1 text-sm text-muted">No affected components recorded.</p>}</div>
    {!compact && <><details id="change-implementation-record" className="border-y border-line py-3"><summary className="cursor-pointer font-semibold">Impact evaluation and approval record</summary><dl className="mt-3 grid gap-4 sm:grid-cols-2">{impact.map(([title,value]) => <Value key={title} title={title} value={value} />)}</dl></details>
    <details id="change-external-evidence" className="border-b border-line pb-3"><summary className="cursor-pointer font-semibold">External decisions, notifications and certification</summary>{evidence ? <dl className="mt-3 grid gap-4 sm:grid-cols-2">{Object.entries(evidence).flatMap(([group, value]) => typeof value === 'object' && value !== null ? Object.entries(value).map(([key, entry]) => <Value key={`${group}-${key}`} title={`${label(group)} · ${label(key)}`} value={typeof entry === 'object' && entry !== null ? Object.entries(entry).map(([id, version]) => `${components.find(c => c.id === id)?.component_uid || id}: ${version}`).join('\n') : entry == null ? undefined : String(entry)} />) : [<Value key={group} title={label(group)} value={value == null ? undefined : String(value)} />])}</dl> : <p className="mt-2 text-sm text-muted">Structured external decisions have not been recorded. Legacy testing status: {change.testing_org_status || 'not recorded'}.</p>}</details>
    {change.rollback && <dl className="grid gap-4 sm:grid-cols-2"><Value title="Rollback reason" value={change.rollback.reason} /><Value title="Rollback outcome" value={change.rollback.outcome} /><Value title="Follow-up action" value={change.rollback.follow_up} /></dl>}</>}
  </section>
}
