import type { ChangeCompliance } from '../../types/changeManagement'
import type { ManagedComponent } from '../../types'

type Group = 'evaluation' | 'certification' | 'deferral' | 'regulator' | 'supplier'
type Field = { key: string; label: string; date?: boolean; multiline?: boolean }
const inputClass = 'mt-1 block w-full min-w-0 rounded-lg border border-line-strong bg-surface px-3 py-2 text-sm text-ink'
function inputDate(value: unknown) {
  if (typeof value !== 'string' || !value) return ''
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
}
export default function ChangeComplianceFields({ value, onChange, components, integrationRelated }: { value: ChangeCompliance; onChange: (value: ChangeCompliance) => void; components: ManagedComponent[]; integrationRelated: boolean }) {
  const group = (name: Group) => (value[name] || {}) as Record<string, unknown>
  const update = (name: Group, key: string, next: unknown) => onChange({ ...value, [name]: { ...group(name), [key]: next } })
  const fields = (name: Group, items: Field[]) => items.map(({ key, label, date, multiline }) => <label key={key} className="text-sm">{label}{multiline ? <textarea rows={2} className={inputClass} value={String(group(name)[key] || '')} onChange={event => update(name, key, event.target.value)} /> : <input type={date ? 'datetime-local' : 'text'} className={inputClass} value={date ? inputDate(group(name)[key]) : String(group(name)[key] || '')} onChange={event => update(name, key, date ? (event.target.value ? new Date(event.target.value).toISOString() : null) : event.target.value)} />}</label>)
  const maximum = Math.max(1, ...components.map(item => item.classification_code))
  const preCertification = components.some(item => item.classification_code === 3 && ['rng', 'game', 'game_platform'].includes(item.regulatory_scope || 'unknown'))
  return <div className="space-y-4 md:col-span-2">
    <div className="space-y-1 border-y border-line py-3"><h4 className="font-semibold">Danish testing and release checks</h4><p className="text-sm text-muted">Record decisions received from the accredited testing organisation (ATO). Internal change approval and ATO certification are separate decisions.</p><p className="text-sm">{preCertification ? 'Code-3 RNG/game changes require certification before implementation. Postponement is unavailable.' : maximum === 3 ? 'Other code-3 changes require certification during or directly after implementation. Quarterly deferral needs ATO permission and an independent qualified QA function.' : maximum === 2 ? 'Code-2 changes require ATO evaluation approval and certification within the annual cycle.' : 'Code-1 changes do not require ATO approval. Formal internal change control still applies.'}</p><a className="text-sm text-accent underline" href="https://spillemyndigheden.dk/media/xjoatyja/scp0600en31-change-management-programme.pdf" target="_blank" rel="noreferrer">SCP.06.00 version 3.1 · sections 4.4–4.5</a></div>
    <details className="space-y-3 border-b border-line pb-3"><summary className="cursor-pointer font-semibold">ATO evaluation decision</summary><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Evaluation decision<select className={inputClass} value={value.evaluation?.status || 'pending'} onChange={event => update('evaluation', 'status', event.target.value)}><option value="pending">Awaiting evaluation</option><option value="approved">Evaluation approved</option><option value="rejected">Evaluation rejected</option></select></label>{fields('evaluation', [{ key: 'provider', label: 'Accredited testing organisation' }, { key: 'reference', label: 'Evaluation decision reference' }, { key: 'evidence', label: 'Evaluation evidence link or document reference' }, { key: 'approved_at', label: 'Evaluation approval received', date: true }])}</div></details>
    <details className="space-y-3 border-b border-line pb-3"><summary className="cursor-pointer font-semibold">Certification and version scope</summary><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Certification outcome<select className={inputClass} value={value.certification?.status || 'pending'} onChange={event => update('certification', 'status', event.target.value)}><option value="pending">Awaiting certification</option><option value="certified">Certified by ATO</option><option value="rejected">Certification rejected</option></select></label>{!preCertification && maximum === 3 && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(value.certification?.continuation_confirmed)} onChange={event => update('certification','continuation_confirmed',event.target.checked)} />ATO confirmed work is a direct continuation of implementation</label>}{!preCertification && maximum === 3 && <label className="text-sm">Certification timing<select className={inputClass} value={value.certification?.timing || ''} onChange={event => update('certification', 'timing', event.target.value || null)}><option value="">Select timing</option><option value="during">During implementation</option><option value="direct_continuation">Direct continuation after implementation</option></select></label>}{fields('certification', [{ key: 'continuation_started_at', label: 'Direct continuation started', date: true }, { key: 'continuation_evidence', label: 'Evidence of uninterrupted ATO work from implementation' }, { key: 'planned_at', label: 'Planned certification date', date: true }, { key: 'schedule_reference', label: 'Agreed certification schedule reference' }, { key: 'provider', label: 'Certifying testing organisation' }, { key: 'reference', label: 'Certificate / standard-report reference' }, { key: 'evidence', label: 'Signed certificate evidence link or reference' }, { key: 'certified_at', label: 'Certification completed', date: true }])}{components.map(item => <label key={item.id} className="text-sm">Certified version of {item.component_uid}<input className={inputClass} value={value.certification?.component_versions?.[item.id] || ''} onChange={event => onChange({ ...value, certification: { ...value.certification, component_versions: { ...value.certification?.component_versions, [item.id]: event.target.value } } })} /></label>) }{components.filter(item => item.classification_code === 3).map(item => <label key={item.id} className="text-sm">Certified hash of {item.component_uid}<input className={inputClass} value={value.certification?.component_checksums?.[item.id] || ''} onChange={event => onChange({ ...value, certification: { ...value.certification, component_checksums: { ...value.certification?.component_checksums, [item.id]: event.target.value } } })} /></label>)}</div></details>
    {!preCertification && maximum === 3 && <details className="space-y-3 border-b border-line pb-3"><summary className="cursor-pointer font-semibold">ATO-approved certification deferral</summary><p className="text-sm text-muted">Only licensed operators and licensed game suppliers can use this option. Record the ATO permission and qualified QA function that is organisationally separate from implementation.</p><div className="grid gap-3 sm:grid-cols-2">{fields('deferral', [{ key: 'permission_reference', label: 'ATO deferral permission reference' }, { key: 'permission_evidence', label: 'ATO deferral permission evidence' }, { key: 'qa_function', label: 'Independent QA function' }, { key: 'due_at', label: 'Deferred certification due', date: true }])}{(['qa_qualified', 'qa_separate'] as const).map((key, index) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(value.deferral?.[key])} onChange={event => update('deferral', key, event.target.checked)} />{index ? 'QA is organisationally separate from implementation' : 'QA staff qualifications have been confirmed'}</label>)}</div></details>}
    <>{maximum === 2 && <div className="grid gap-3 sm:grid-cols-2">{(['annual_certification_provider','annual_certification_evidence'] as const).map((key,index) => <label key={key} className="text-sm">{index ? 'Annual certification cadence evidence' : 'Annual certifying testing organisation'}<input className={inputClass} value={value[key] || ''} onChange={event => onChange({...value,[key]:event.target.value})} /></label>)}<label className="text-sm">Code-2 certification cadence report reference<input className={inputClass} value={value.annual_certification_reference || ''} onChange={event => onChange({...value,annual_certification_reference:event.target.value})} /></label>{(['annual_certification_anchor_at', 'annual_certification_due_at'] as const).map((key, index) => <label key={key} className="text-sm">{index ? 'Code-2 certification due' : 'Code-2 certification cadence anchor'}<input type="datetime-local" className={inputClass} value={inputDate(value[key])} onChange={event => onChange({ ...value, [key]: event.target.value ? new Date(event.target.value).toISOString() : null })} /></label>)}</div>}
    </><details className="space-y-3 border-b border-line pb-3"><summary className="cursor-pointer font-semibold">Regulator notifications and decisions</summary><p className="text-sm text-muted">Record actual notifications and decisions made outside CAP. RNG notifications must precede implementation by five Danish working days. Identified or suspected errors require immediate notification.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Error notification timeliness<select className={inputClass} value={value.regulator?.error_notice_immediate == null ? '' : String(value.regulator.error_notice_immediate)} onChange={event => update('regulator', 'error_notice_immediate', event.target.value ? event.target.value === 'true' : null)}><option value="">Not assessed / no error identified</option><option value="true">Notification made immediately</option><option value="false">Notification was delayed</option></select></label>{fields('regulator', [{ key: 'rng_notified_at', label: 'RNG notification sent', date: true }, { key: 'rng_reference', label: 'RNG notification receipt reference' }])}<label className="text-sm">Prior game approval needed?<select className={inputClass} value={value.regulator?.game_approval_required == null ? '' : String(value.regulator.game_approval_required)} onChange={event => update('regulator', 'game_approval_required', event.target.value ? event.target.value === 'true' : null)}><option value="">Not assessed</option><option value="true">Yes — record authority approval</option><option value="false">No — assessed as not required</option></select></label>{fields('regulator', [{ key: 'game_approval_reference', label: 'Prior game approval reference' }, { key: 'game_approval_at', label: 'Prior game approval received', date: true }, { key: 'game_approval_basis', label: 'Game approval applicability assessment', multiline: true }, { key: 'error_identified_at', label: 'Error identified or suspected', date: true }, { key: 'error_notified_at', label: 'Error notification sent', date: true }, { key: 'error_reference', label: 'Error notification receipt reference' }])}</div></details>
    <details className="space-y-3 border-b border-line pb-3"><summary className="cursor-pointer font-semibold">Supplier recommendation and responsibility</summary><div className="grid gap-3 sm:grid-cols-2">{fields('supplier', [{ key: 'recommended_at', label: 'Supplier recommendation received', date: true }, { key: 'delay_justification', label: 'Reason for time until implementation', multiline: true }, { key: 'whole_system_evaluation', label: 'Operator evaluation of whole-system impact', multiline: true }, { key: 'rejection_attestation', label: 'ATO attestation of a rejected supplier recommendation' }, { key: 'rejection_ato', label: 'ATO reviewing the rejection' }, { key: 'rejection_evidence', label: 'Rejection attestation evidence reference' }])}</div></details>
    {integrationRelated && <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Approved integration procedure reference<input className={inputClass} value={value.integration_procedure_reference || ''} onChange={event => onChange({ ...value, integration_procedure_reference: event.target.value })} /></label><label className="text-sm">Integration requirements checked<input className={inputClass} placeholder="SCP.02 reference, SCP.07 reference" value={(value.integration_requirement_references || []).join(', ')} onChange={event => onChange({ ...value, integration_requirement_references: event.target.value.split(',').map(item => item.trim()).filter(Boolean) })} /></label><p className="text-sm text-muted sm:col-span-2">After implementation, record the completed base/game-platform checks and evidence in this change before verification.</p></div>}
  </div>
}
