import { beforeEach, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import AccountSettings from '../pages/AccountSettings'
import ProfileDropdown from '../components/ProfileDropdown'
import api from '../api/client'

const { logout, refreshUser } = vi.hoisted(() => ({ logout: vi.fn(), refreshUser: vi.fn() }))
vi.mock('../contexts/AuthContext', () => ({ useAuth: () => ({ user: { id: 'me', full_name: 'Test User', email: 'test@example.com', role: 'contributor' }, logout, refreshUser }) }))
vi.mock('../api/client', () => ({ default: { get: vi.fn(), patch: vi.fn(), post: vi.fn() } }))
function settings(section = 'account') {
  render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}><MemoryRouter initialEntries={[`/account?section=${section}`]}><AccountSettings /></MemoryRouter></QueryClientProvider>)
}
beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(api.get).mockResolvedValue({ data: { review_mentions: true, review_reminders: true } })
  vi.mocked(api.patch).mockImplementation(async (url, value) => ({ data: url === '/auth/me' ? { full_name: 'New Name' } : value }))
  vi.mocked(api.post).mockResolvedValue({ data: {} })
})
it('opens profile options from the keyboard, dismisses them and signs out', async () => {
  render(<MemoryRouter><ProfileDropdown /></MemoryRouter>)
  const trigger = screen.getByRole('button', { name: 'Profile options' })
  fireEvent.keyDown(trigger, { key: 'ArrowDown' })
  const link = screen.getByRole('link', { name: 'Account settings' })
  await waitFor(() => expect(link).toHaveFocus())
  expect(link).toHaveAttribute('href', '/account?section=account')
  expect(screen.getByRole('link', { name: 'Notification settings' })).toHaveAttribute('href', '/account?section=notifications')
  fireEvent.keyDown(document, { key: 'Escape' })
  expect(trigger).toHaveFocus()
  expect(trigger).toHaveAttribute('aria-expanded', 'false')
  fireEvent.click(trigger)
  fireEvent.pointerDown(document.body)
  expect(trigger).toHaveAttribute('aria-expanded', 'false')
  fireEvent.click(trigger)
  fireEvent.click(screen.getByRole('button', { name: 'Logout' }))
  await waitFor(() => expect(logout).toHaveBeenCalledOnce())
})
it('refreshes the displayed identity after saving a profile', async () => {
  settings()
  fireEvent.change(screen.getByLabelText('Full name'), { target: { value: 'New Name' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save profile' }))
  await screen.findByText('Profile saved.')
  expect(api.patch).toHaveBeenCalledWith('/auth/me', { full_name: 'New Name' })
  expect(refreshUser).toHaveBeenCalledOnce()
})
it('retains rejected password inputs and clears them after success', async () => {
  settings()
  const current = screen.getByLabelText('Current password')
  const next = screen.getByLabelText('New password')
  const confirm = screen.getByLabelText('Confirm new password')
  fireEvent.change(current, { target: { value: 'old-password' } })
  fireEvent.change(next, { target: { value: 'new-password' } })
  fireEvent.change(confirm, { target: { value: 'different' } })
  fireEvent.click(screen.getByRole('button', { name: 'Change password' }))
  expect(screen.getByRole('alert')).toHaveTextContent('do not match')
  expect(api.post).not.toHaveBeenCalled()
  fireEvent.change(confirm, { target: { value: 'new-password' } })
  vi.mocked(api.post).mockRejectedValueOnce(new Error('Request failed'))
  fireEvent.click(screen.getByRole('button', { name: 'Change password' }))
  await screen.findByText('Your password could not be changed. Try again.')
  expect(current).toHaveValue('old-password')
  fireEvent.click(screen.getByRole('button', { name: 'Change password' }))
  await screen.findByText('Password changed. You are still signed in on this browser.')
  expect(current).toHaveValue('')
  expect(next).toHaveValue('')
  expect(confirm).toHaveValue('')
})
it('retains notification choices after a failed save for retry', async () => {
  settings('notifications')
  const mentions = await screen.findByRole('checkbox', { name: /Mentions in review comments/ })
  fireEvent.click(mentions)
  vi.mocked(api.patch).mockRejectedValueOnce(new Error('Request failed'))
  fireEvent.click(screen.getByRole('button', { name: 'Save notification settings' }))
  await screen.findByText('Notification settings could not be saved. Try again.')
  expect(mentions).not.toBeChecked()
  expect(screen.getByRole('button', { name: 'Save notification settings' })).toBeEnabled()
  vi.mocked(api.get).mockResolvedValue({ data: { review_mentions: false, review_reminders: true } })
  fireEvent.click(screen.getByRole('button', { name: 'Save notification settings' }))
  await screen.findByText('Notification settings saved.')
  expect(api.patch).toHaveBeenLastCalledWith('/auth/notification-settings', { review_mentions: false, review_reminders: true })
  expect(mentions).not.toBeChecked()
})

it('shows each password independently without submitting or changing its value', () => {
  settings()
  const current = screen.getByLabelText('Current password')
  const next = screen.getByLabelText('New password')
  fireEvent.change(current, { target: { value: 'entered-password' } })
  expect(current).toHaveAttribute('type', 'password')
  fireEvent.click(screen.getByRole('button', { name: 'Show current password' }))
  expect(current).toHaveAttribute('type', 'text')
  expect(current).toHaveValue('entered-password')
  expect(next).toHaveAttribute('type', 'password')
  expect(api.post).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Hide current password' }))
  expect(current).toHaveAttribute('type', 'password')
  expect(current).toHaveValue('entered-password')
})
