import { test, expect, type APIResponse } from '@playwright/test'
import { loginAsAdmin } from './testCredentials'
async function data(response: APIResponse) {expect(response.ok(),await response.text()).toBeTruthy();return response.json()}
test.use({timezoneId:'UTC'})
const ago=(days:number)=>new Date(Date.now()-days*86400000).toISOString()
for (const width of [1440,390]) for (const theme of ['light','dark']) test(`Danish change record, draft protection and lifecycle at ${width}px in ${theme}`,async ({page}) => {
  await page.setViewportSize({width,height:950})
  await page.addInitScript(value=>localStorage.setItem('cap:theme',value),theme)
  await loginAsAdmin(page);await page.waitForURL('/')
  const csrf=(await page.context().cookies()).find(cookie=>cookie.name==='csrf_token')!
  await page.context().setExtraHTTPHeaders({'X-CSRF-Token':csrf.value})
  const jurisdictions=await data(await page.request.get('/api/v1/jurisdictions?limit=1000'))
  let jurisdiction=jurisdictions.items.find((item:{code:string})=>item.code.toLowerCase()==='dk')
  if (!jurisdiction) jurisdiction=await data(await page.request.post('/api/v1/jurisdictions',{data:{code:'dk',name:'Denmark',active:true}}))
  const existingRegisters=await data(await page.request.get(`/api/v1/change-management/registers?jurisdiction_id=${jurisdiction.id}&limit=1000`))
  for (const existing of existingRegisters.items.filter((item:{status:string})=>item.status==='active')) await data(await page.request.patch(`/api/v1/change-management/registers/${existing.id}`,{data:{status:'inactive'}}))
  const register=await data(await page.request.post('/api/v1/change-management/registers',{data:{jurisdiction_id:jurisdiction.id,name:`Danish synthetic ${width} ${theme} ${Date.now()}`,responsibility_role:'licensed_operator',programme_assurance:{change_plan_reference:'PLAN-1',change_plan_approved_at:ago(30),change_plan_approved_by:'Senior management',change_plan_approval_evidence:'Signed plan',responsible_owner:'Compliance',ato_accreditation_reference:'ACC-1',ato_accreditation_evidence:'Accreditation scope',latest_certification_at:ago(30),certification_reference:'SCP06-1',certification_evidence:'Signed standard report',certification_ato:'Synthetic accredited laboratory',report_submitted_at:ago(29)}}}))
  const component=await data(await page.request.post(`/api/v1/change-management/registers/${register.id}/components`,{data:{component_uid:`SYN-${width}-${theme}-${Date.now()}`,definition:'Synthetic ancillary component',version:'1.0',identifying_characteristics:'Test-only package',change_owner_name:'Operations',regulatory_scope:'other',confidentiality_code:1,integrity_code:1,availability_code:1,accountability_code:1}}))
  await data(await page.request.post(`/api/v1/change-management/registers/${register.id}/baselines`,{data:{label:'Synthetic certified platform baseline',certification_scope:'whole_platform',certification_at:ago(30),certification_reference:'PLATFORM-1',certification_evidence:'Synthetic whole-platform report',certification_ato:'Synthetic accredited laboratory'}}))
  const change=await data(await page.request.post(`/api/v1/change-management/registers/${register.id}/changes`,{data:{title:'Synthetic Danish release',description:'Replace an ancillary component',justification:'Planned maintenance',category:'operations',complexity_classification:'low',resource_assessment:'One engineer',scheduling_assessment:'Agreed window',planned_start_at:ago(0),planned_end_at:new Date(Date.now()+3600000).toISOString(),evaluation_effect:'Service retained',evaluation_risk:'Low',evaluation_regulatory_impact:'No gaming behaviour affected',evaluation_ciaa_impact:'No relevance',components:[{component_id:component.id,planned_version:'1.1'}]}}))
  await page.goto(`/change-management?change=${change.id}&tab=changes`)
  await expect(page.getByRole('heading',{name:'Synthetic Danish release',level:2})).toBeVisible()
  await expect(page.getByText('Replace an ancillary component',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Approve change',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'← Back to changes',exact:true}).click()
  await page.getByRole('button',{name:'New change',exact:true}).click()
  const editor=page.getByRole('dialog',{name:'New change'})
  await editor.getByLabel('Change title',{exact:true}).fill('Interrupted synthetic draft')
  await page.keyboard.press('Escape')
  const discard=page.getByRole('dialog',{name:'Discard unsaved changes?'})
  await expect(discard).toBeVisible();await discard.getByRole('button',{name:'Cancel',exact:true}).click()
  await expect(editor.getByLabel('Change title',{exact:true})).toHaveValue('Interrupted synthetic draft')
  await editor.getByRole('button',{name:'Cancel',exact:true}).click();await discard.getByRole('button',{name:'Discard changes',exact:true}).click()
  await page.goto(`/change-management?change=${change.id}&tab=changes`)
  await page.getByRole('button',{name:'Approve change',exact:true}).click()
  const approval=page.getByRole('dialog',{name:'Approve: Synthetic Danish release'})
  await expect(approval.getByText('Replace an ancillary component',{exact:true})).toBeVisible()
  await approval.getByLabel('Enter required rationale',{exact:true}).fill('Approved synthetic scope')
  await approval.getByRole('button',{name:'Approve Change',exact:true}).click()
  await expect(page.getByRole('button',{name:'Record implementation',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'Record implementation',exact:true}).click()
  const implementation=page.getByRole('dialog',{name:'Implement: Synthetic Danish release'})
  await implementation.getByLabel('Enter required rationale',{exact:true}).fill('Observed component version recorded')
  const approved=await data(await page.request.get(`/api/v1/change-management/changes/${change.id}`))
  // An implementation timestamp must follow its approval; retain seconds for this boundary.
  await expect.poll(()=>Math.floor(Date.now()/1000)*1000).toBeGreaterThan(new Date(approved.approved_at).getTime())
  // Native datetime-local inputs omit zero seconds from their canonical value.
  const stamp=new Date(Math.floor(Date.now()/1000)*1000).toISOString().slice(0,19).replace(/:00$/,'')
  await implementation.getByLabel('Implemented Start',{exact:true}).fill(stamp)
  await implementation.getByLabel('Implemented End',{exact:true}).fill(stamp)
  await implementation.getByLabel(/actual version/).fill('1.1')
  await implementation.getByRole('button',{name:'Implement Change',exact:true}).click()
  await expect(page.getByRole('button',{name:'Verify',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'Verify',exact:true}).click()
  const verification=page.getByRole('dialog',{name:'Verify: Synthetic Danish release'})
  await verification.getByLabel('Enter required rationale',{exact:true}).fill('Approved scope matches actual component')
  await verification.getByRole('button',{name:'Verify Change',exact:true}).click()
  expect(await page.locator('html').evaluate(node=>node.classList.contains('dark'))).toBe(theme==='dark')
  await expect(page.getByText('Internally verified',{exact:true})).toBeVisible()
  const activity=page.getByRole('heading',{name:'Activity Timeline',exact:true}).locator('..')
  await expect(activity.getByText('Approved scope matches actual component',{exact:true})).toBeVisible()
  if (process.env.CAP_REVIEW_EVIDENCE_DIR) await page.screenshot({path:`${process.env.CAP_REVIEW_EVIDENCE_DIR}/change-${width}-${theme}.png`,fullPage:true})
  const persisted=await data(await page.request.get(`/api/v1/change-management/changes/${change.id}`))
  expect(persisted.status).toBe('verified');expect(persisted.components[0].implemented_version).toBe('1.1');expect(persisted.components[0].frozen_snapshot.component_uid).toBe(component.component_uid)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.getByRole('button',{name:'Programme assurance',exact:true}).click()
  await expect(page.getByText('Programme evidence recorded',{exact:true})).toBeVisible()
  if (process.env.CAP_REVIEW_EVIDENCE_DIR) await page.screenshot({path:`${process.env.CAP_REVIEW_EVIDENCE_DIR}/programme-${width}-${theme}.png`,fullPage:true})
})
