import { expect, test, type Page, type APIResponse, type TestInfo } from '@playwright/test'
import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { loginAsAdmin, e2eAdminPassword } from './testCredentials'

// Only market/user/reference fixtures use APIs. Work is created and progressed through the UI.
async function json(response: APIResponse) { expect(response.ok(), await response.text()).toBeTruthy(); return response.json() }
async function signIn(page: Page) {
  await loginAsAdmin(page); await page.waitForURL('/')
  const csrf = (await page.context().cookies()).find(cookie => cookie.name === 'csrf_token')!
  await page.context().setExtraHTTPHeaders({ 'X-CSRF-Token': csrf.value })
}
async function market(page: Page, code: string, name: string) {
  const markets = await json(await page.request.get('/api/v1/jurisdictions?limit=1000'))
  const existing = markets.items.find((entry: { code: string }) => entry.code.toUpperCase() === code)
  expect(existing, `${name} reference fixture`).toBeDefined()
  const item = existing
  await page.reload(); await page.getByLabel('Jurisdiction selector').selectOption(item.id)
  return item.id
}
async function startPack(page: Page, name: string, people = '', foreign = false) {
  await page.goto('/licence-applications')
  await page.getByRole('button', { name: 'New licence pack', exact: true }).click()
  await page.getByLabel('Pack name', { exact: true }).fill(name)
  await page.getByLabel('Applicant', { exact: true }).fill('Synthetic Operator Ltd')
  await page.getByLabel('Activities and scope').fill('Synthetic online casino and betting preparation')
  await page.getByRole('button', { name: 'Continue to market questions' }).click()
  if (foreign) {
    await page.getByRole('checkbox', { name: /applicant.*(abroad|outside)/i }).check()
    await page.getByRole('checkbox', { name: /Finnish.*(ID|identity)|without.*Finnish/i }).check()
  }
  if (people) await page.getByRole('textbox', { name: /People|persons|individual/i }).fill(people)
  await page.getByRole('button', { name: 'Review proposed contents' }).click()
}
async function finishPack(page: Page) {
  await page.getByRole('checkbox', { name: 'I have reviewed this proposed checklist for this application.' }).check()
  await page.getByRole('button', { name: 'Continue to owners and access' }).click()
  const response = page.waitForResponse(r => r.url().endsWith('/applications/guided') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create licence pack', exact: true }).click()
  const item = await json(await response)
  await expect(page).toHaveURL(new RegExp(`application=${item.id}`))
  await expect(page.getByRole('heading', { name: item.name, exact: true })).toBeVisible()
  return item
}
async function capture(page: Page, info: TestInfo, label: string) {
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: info.outputPath(`${label}.png`), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
}
async function tab(page: Page, name: string) { await page.getByRole('button', { name, exact: true }).click() }
async function setupForm(page: Page, name: string, label: string) {
  await tab(page, 'Forms and documents')
  const row = page.locator('article').filter({ has: page.getByRole('heading', { name, exact: true }) })
  await row.getByRole('button', { name: `Set up ${name}`, exact: true }).click()
  await row.getByRole('button', { name: 'Add question', exact: true }).click()
  await row.getByLabel('Question 1', { exact: true }).fill(label)
  await row.getByRole('button', { name: 'Save form or document', exact: true }).click()
  await row.getByRole('button', { name: `Open ${name}`, exact: true }).click()
  const input = page.getByRole('textbox', { name: label, exact: true })
  await input.fill('Synthetic verified answer')
  await expect(page.getByRole('button', { name: 'Accept response', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Accept response', exact: true }).click()
  await expect(page.getByText('Accepted', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Return to pack', exact: false }).click()
}
test.use({ actionTimeout: 15000 })
test.beforeEach(async ({ page }) => { await signIn(page) })

test('blank market pack skips empty steps and continues directly to its form workspace', async ({ page }, info) => {
  await market(page, 'SE', 'Sweden')
  await page.goto('/licence-applications?create=1')
  await page.getByLabel('Pack name', { exact: true }).fill('Synthetic Swedish licence pack')
  await expect(page.getByText('Step 1 of 2')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Continue to market questions' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Continue to owners and access' }).click()
  await expect(page.getByText('Step 2 of 2')).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /reviewed this proposed checklist/ })).toHaveCount(0)
  const response = page.waitForResponse(r => r.url().endsWith('/applications/guided') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create licence pack', exact: true }).click()
  const pack = await json(await response)
  expect(pack.components).toHaveLength(0)
  await expect(page.getByRole('heading', { name: pack.name, level: 1 })).toBeVisible()
  await page.getByRole('button', { name: 'Continue to forms and documents' }).click()
  await expect(page).toHaveURL(/tab=forms/)
  await expect(page.getByLabel('Form or document name')).toBeVisible()
  await capture(page, info, 'blank-pack-workspace-desktop')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await capture(page, info, 'blank-pack-workspace-mobile-dark')
})

test('Danish UI journey: repeated declarations, documents, internal approval, export, submission, queries and revision', async ({ page }, info) => {
  test.setTimeout(180000)
  await market(page, 'DK', 'Denmark')
  await startPack(page, 'Danish UI walkthrough', 'Director One\nDirector Two')
  await expect(page.getByLabel('Item 1', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Item 2', { exact: true })).toHaveValue(/Director One/)
  await expect(page.getByLabel('Item 3', { exact: true })).toHaveValue(/Director Two/)
  await capture(page, info, 'denmark-proposed-contents')
  const pack = await finishPack(page)
  expect(pack.profile_snapshot.code.toUpperCase()).toBe('DK')
  expect(pack.components.filter((item: { kind: string }) => item.kind !== 'document')).toHaveLength(4)
  expect(pack.snapshots).toHaveLength(0)
  for (const [index, item] of pack.components.filter((entry: { kind: string }) => entry.kind !== 'document').entries()) await setupForm(page, item.name, `Synthetic source question ${index + 1}`)
  await tab(page, 'Forms and documents')
  await page.locator('summary').filter({ hasText: /^Add form or document$/ }).click()
  await page.getByLabel('Form or document name').fill('Additional application form')
  await page.getByLabel('Item type', { exact: true }).selectOption('form')
  await page.getByRole('button', { name: 'Add question', exact: true }).click()
  await page.getByLabel('Question 1', { exact: true }).fill('Additional application answer')
  await page.getByRole('button', { name: 'Add form or document', exact: true }).click()
  await page.getByRole('button', { name: 'Open Additional application form', exact: true }).click()
  await page.getByRole('textbox', { name: 'Additional application answer', exact: true }).fill('Synthetic additional application answer')
  await page.getByRole('button', { name: 'Accept response', exact: true }).click()
  await expect(page.getByText('Accepted', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Return to pack', exact: false }).click()
  await tab(page, 'Forms and documents')
  for (const item of pack.components.filter((entry: { kind: string }) => entry.kind === 'document')) {
    const row = page.locator('article').filter({ has: page.getByRole('heading', { name: item.name, exact: true }) })
    await row.getByRole('button', { name: `Edit ${item.name}`, exact: true }).click()
    await row.getByLabel('Upload a private source file').setInputFiles('e2e/fixtures/test.pdf')
    await row.getByRole('button', { name: 'Upload and attach', exact: true }).click()
    await expect(row.getByText('test.pdf', { exact: true }).first()).toBeVisible()
    await row.getByRole('button', { name: 'Save form or document', exact: true }).click()
  }
  await capture(page, info, 'denmark-completed-pack')
  await tab(page, 'Approval and submission')
  await expect(page.getByText('Ready for internal approval', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Send for internal review', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm: Send for internal review' }).click()
  await page.getByRole('button', { name: 'Approve pack internally', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm: Approve and freeze pack' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download version 1', exact: true }).click()
  const exported = await download
  const bytes = await readFile((await exported.path())!)
  expect(bytes.subarray(0, 2).toString()).toBe('PK')
  const approvedHash = createHash('sha256').update(bytes).digest('hex')
  await page.getByRole('button', { name: 'Record submission', exact: true }).click()
  await page.getByLabel('Submission reference').fill('DK-SYNTHETIC-001')
  await page.getByRole('button', { name: 'Confirm: Record submission' }).click()
  await expect(page.getByText(/DK-SYNTHETIC-001/)).toBeVisible()
  await page.getByRole('button', { name: 'Start follow-up', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm: Start follow-up' }).click()
  await page.locator('summary').filter({ hasText: /^Add authority query$/ }).click()
  await page.getByLabel('Authority query', { exact: true }).fill('Synthetic authority query: clarify applicant scope')
  await page.getByRole('button', { name: 'Add authority query', exact: true }).click()
  await page.getByLabel('Response', { exact: true }).fill('Clarification recorded with the applicant')
  await expect(page.getByRole('button', { name: 'Resolve query', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Resolve query', exact: true }).click()
  await page.getByRole('button', { name: 'Record outcome', exact: true }).click()
  await page.getByLabel('Authority decision / outcome').fill('Synthetic authority decision: application withdrawn, no licence issued')
  await page.getByRole('button', { name: 'Confirm: Record outcome and complete' }).click()
  await expect(page.getByText('Synthetic authority decision: application withdrawn, no licence issued', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Return to draft', exact: true }).click()
  await page.getByLabel('Reason for reopening').fill('Synthetic corrected applicant information')
  await page.getByRole('button', { name: 'Confirm: Return to draft' }).click()
  const secondDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download version 1', exact: true }).click()
  const oldBytes = await readFile((await (await secondDownload).path())!)
  expect(createHash('sha256').update(oldBytes).digest('hex')).toBe(approvedHash)
  const persisted = await json(await page.request.get(`/api/v1/applications/${pack.id}`))
  expect(persisted.status).toBe('draft'); expect(persisted.snapshots).toHaveLength(1)
  expect(persisted.snapshots[0].reference).toBe('DK-SYNTHETIC-001')
  await tab(page, 'History'); await capture(page, info, 'denmark-history')
})

for (const foreign of [false, true]) test(`Finnish UI setup: ${foreign ? 'foreign applicant and people without Finnish ID' : 'domestic applicant'}`, async ({ page }, info) => {
  await market(page, 'FI', 'Finland')
  await startPack(page, `Finnish ${foreign ? 'foreign' : 'domestic'} UI pack`, foreign ? 'Responsible Person' : '', foreign)
  const proposed = await page.getByLabel(/^Item \d+$/).evaluateAll(nodes => nodes.map(node => (node as HTMLInputElement).value))
  expect(proposed.some(name => /Foreign applicant/.test(name))).toBe(foreign)
  expect(proposed.some(name => /Responsible Person/.test(name))).toBe(foreign)
  await expect(page.getByText(/before.*operat|before operations/i).first()).toBeVisible()
  await capture(page, info, `finland-${foreign ? 'foreign' : 'domestic'}-contents`)
  const pack = await finishPack(page)
  expect(pack.status).toBe('draft')
  expect(pack.profile_snapshot.code.toUpperCase()).toBe('FI')
  expect(pack.components.length).toBe(proposed.length)
})

test('resumable setup and failed save preserve choices without copying personal declarations', async ({ page }) => {
  await market(page, 'DK', 'Denmark')
  await startPack(page, 'Resumable Danish pack', 'Private Person')
  await page.getByLabel('Item 1', { exact: true }).fill('Main application edited')
  await page.reload()
  await expect(page.getByLabel('Item 1', { exact: true })).toHaveValue('Main application edited')
  await expect(page.getByLabel(/^Item \d+$/)).toHaveCount(4)
  await expect(page.getByRole('alert').filter({ hasText: 'Re-enter the people' })).toBeVisible()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(page.getByRole('textbox', { name: /People|persons|individual/i })).toHaveValue('')
  await page.getByRole('textbox', { name: /People|persons|individual/i }).fill('Private Person')
  await page.getByRole('button', { name: 'Review proposed contents' }).click()
  await page.getByRole('checkbox', { name: 'I have reviewed this proposed checklist for this application.' }).check()
  await page.getByRole('button', { name: 'Continue to owners and access' }).click()
  await page.route('**/api/v1/applications/guided', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Synthetic save failure' }) }))
  await page.getByRole('button', { name: 'Create licence pack', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Synthetic save failure' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Create licence pack', exact: true })).toBeEnabled()
  await page.unroute('**/api/v1/applications/guided')
  const response = page.waitForResponse(r => r.url().endsWith('/applications/guided') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create licence pack', exact: true }).click(); await json(await response)
})

test('certification UI progresses from draft setup through evidence, assessment, package approval and history', async ({ page }, info) => {
  test.setTimeout(120000)
  await page.goto('/certification-projects')
  await page.getByRole('button', { name: 'Start certification', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Project name', { exact: true }).fill('Synthetic audit engagement')
  await dialog.getByLabel('Project jurisdiction').selectOption({ label: 'Example jurisdiction' })
  await dialog.getByLabel('Test lab or provider (optional)').fill('Synthetic Assurance Lab')
  const response = page.waitForResponse(r => r.url().endsWith('/certification-projects') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Start certification', exact: true }).click()
  const project = await json(await response)
  await page.goto(`/certification-projects?project=${project.id}`)
  await expect(page.getByRole('button', { name: 'Choose approved requirements' })).toBeVisible()
  await tab(page, 'Requirements and evidence')
  await expect(page.getByRole('button', { name: 'Create submission assessment', exact: true })).toBeDisabled()
  await page.getByRole('checkbox', { name: /E2E Document/ }).check()
  await page.getByRole('button', { name: 'Save baseline', exact: true }).click()
  const baselineConfirmation = page.getByRole('dialog', { name: 'Confirm project baseline changes', exact: true })
  await expect(baselineConfirmation.getByText('Add E2E Document: approved v1', { exact: true })).toBeVisible()
  await baselineConfirmation.getByRole('button', { name: 'Confirm baseline changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Create submission assessment', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Create submission assessment', exact: true }).click()
  await page.getByRole('button', { name: 'Add form', exact: true }).click()
  const forms = page.getByRole('region', { name: 'Project forms and evidence' })
  const formEditor = page.getByRole('dialog', { name: 'Add project form', exact: true })
  await page.keyboard.press('Escape')
  await expect(formEditor).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Add form', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Add form', exact: true }).click()
  await formEditor.getByLabel('Form name', { exact: true }).fill('Audit supporting questionnaire')
  await page.keyboard.press('Escape')
  await page.getByRole('dialog', { name: 'Discard this form draft?', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(formEditor.getByLabel('Form name', { exact: true })).toHaveValue('Audit supporting questionnaire')
  await capture(page, info, 'project-form-dialog')
  await formEditor.getByRole('button', { name: 'Add question', exact: true }).click()
  await formEditor.getByLabel('Question 1', { exact: true }).fill('Audit supporting answer')
  await formEditor.getByRole('button', { name: 'Create form', exact: true }).click()
  await expect(forms.getByRole('link', { name: 'Audit supporting questionnaire', exact: true })).toBeVisible()
  await forms.getByRole('link', { name: 'Audit supporting questionnaire', exact: true }).click()
  await page.getByRole('textbox', { name: 'Audit supporting answer', exact: true }).fill('Synthetic answer backed by the audit record')
  await expect(page.getByRole('button', { name: 'Accept response', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Accept response', exact: true }).click()
  await expect(page.getByText('Accepted', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Return to certification project/ }).click()
  await tab(page, 'Testing and findings')
  await page.getByLabel('System version', { exact: true }).fill('Platform v1.2.3')
  await page.getByRole('button', { name: 'Save engagement', exact: true }).click()
  await page.getByRole('link', { name: 'Open assessment and findings' }).click()
  await page.getByLabel('Evidence for REQ-001', { exact: true }).fill('Synthetic audit test evidence for Platform v1.2.3')
  await page.getByLabel('Requirement status for REQ-001', { exact: true }).selectOption('evidenced')
  await page.getByLabel('Reviewer decision for REQ-001', { exact: true }).selectOption('confirmed')
  await expect(page.getByRole('button', { name: 'Complete assessment', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Complete assessment', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Complete and freeze' }).click()
  await expect(page.getByRole('heading', { name: 'Completed assessment' })).toBeVisible()
  await page.getByRole('link', { name: 'Back to certification project' }).click()
  await tab(page, 'Reports and submission')
  await page.getByLabel('Report reference', { exact: true }).fill('SYNTHETIC-AUDIT-01')
  await page.getByLabel('Recorded report outcome').selectOption('passed_with_findings')
  await page.getByRole('button', { name: 'Save report', exact: true }).click()
  await expect(page.getByLabel('Report reference', { exact: true })).toHaveValue('SYNTHETIC-AUDIT-01')
  await expect(page.getByLabel('Recorded report outcome')).toHaveValue('passed_with_findings')
  await page.getByLabel('Package version', { exact: true }).fill('v1')
  for (const label of ['Submission assessment is closed', 'Submission package is bound to the assessment snapshot', 'All required documents are included']) {
    await page.getByRole('checkbox', { name: label, exact: true }).check()
  }
  await page.getByRole('button', { name: 'Add package', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Request approval', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Request approval', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Approve', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Approve', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Lock + handoff', exact: true })).toBeVisible()
  const current = await json(await page.request.get(`/api/v1/certification-projects/${project.id}`))
  const packages = await json(await page.request.get(`/api/v1/submission-packages?project_id=${project.id}&limit=100`))
  expect(current.report_outcome).toBe('passed_with_findings')
  expect(current.stage).not.toBe('regulator_approval')
  expect(packages.items.find((item: { version: string }) => item.version === 'v1')).toMatchObject({ status: 'approved' })
  await capture(page, info, 'certification-report-and-submission')
  await tab(page, 'History')
  await expect(page.getByRole('heading', { name: 'Earlier assessments and maintenance' })).toBeVisible()
  await page.locator('summary').filter({ hasText: /^Add maintenance plan$/ }).click()
  await page.getByLabel('Plan name').fill('Synthetic annual audit follow-up')
  await page.getByLabel('First due date').fill('2030-01-15')
  await page.getByRole('button', { name: 'Add plan', exact: true }).click()
  await expect(page.getByText('Synthetic annual audit follow-up', { exact: true })).toBeVisible()
  await capture(page, info, 'certification-history')
})

// One batched capture set for populated work, creation, help and shared administration.
test('visual batch: both themes, desktop tablet and 320px, with real pack and certification screens', async ({ page }, info) => {
  test.setTimeout(180000)
  const packs = await json(await page.request.get('/api/v1/applications?q=Danish%20UI%20walkthrough&limit=1'))
  const pack = packs.items.find((entry: { name: string }) => entry.name === 'Danish UI walkthrough')
  expect(pack).toBeDefined()
  const projects = await json(await page.request.get('/api/v1/certification-projects?limit=20'))
  const project = projects.items.find((entry: { name: string }) => entry.name === 'Synthetic audit engagement')
  expect(project).toBeDefined()
  const routes: Record<string, string> = {
    creation: '/licence-applications',
    form: `/preparation?case=${pack.components.find((entry: { case_id: string | null }) => entry.case_id)?.case_id}`,
    pack: `/licence-applications?application=${pack.id}&tab=forms`,
    approval: `/licence-applications?application=${pack.id}&tab=approval`,
    certification: `/certification-projects?project=${project.id}&section=testing`,
    dashboard: '/', teams: '/access-teams', help: '/guide', reports: '/reports', change: '/change-management', requirements: '/requirements', setup: '/market-setup',
  }
  for (const theme of ['light', 'dark']) {
    await page.evaluate(value => localStorage.setItem('cap:theme', value), theme)
    for (const width of [1280, 768, 320]) {
      await page.setViewportSize({ width, height: 900 })
      for (const [name, route] of Object.entries(routes)) {
        await page.goto(route)
        await expect(page.locator('main h1').first()).toBeVisible()
        await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
        await expect(page.getByText(/^Loading/i).and(page.locator(':visible'))).toHaveCount(0)
        await expect(page.getByRole('heading', { name: 'Page not found', exact: true })).toHaveCount(0)
        if (name === 'dashboard') await expect(page.getByRole('heading', { name: 'Compliance Dashboard', exact: true })).toBeVisible()
        await capture(page, info, `${name}-${theme}-${width}`)
      }
    }
  }
})
