import { readFileSync } from 'node:fs'
import { test, expect, type Page, type APIResponse, type Browser } from '@playwright/test'
import { e2eAdminPassword, loginAsAdmin } from './testCredentials'

// Full Chromium supplies the native PDF viewer that headless-shell omits.
if (process.env.CAP_PILOT_CHROMIUM_EXECUTABLE) test.use({ channel: 'chromium', launchOptions: { executablePath: process.env.CAP_PILOT_CHROMIUM_EXECUTABLE } })
test.setTimeout(180_000)
const pdfBytes = readFileSync('e2e/fixtures/test.pdf')
async function capture(page: Page, path: string) {
  await page.waitForLoadState('networkidle')
  await page.evaluate(() => { (document.activeElement as HTMLElement)?.blur(); window.scrollTo(0, 0) })
  await page.screenshot({ path, fullPage: true })
}
async function json(response: APIResponse) { expect(response.ok(), await response.text()).toBeTruthy(); return response.json() }
async function csrf(page: Page) {
  const token = (await page.context().cookies()).find(cookie => cookie.name === 'csrf_token')!
  await page.context().setExtraHTTPHeaders({ 'X-CSRF-Token': token.value })
}
async function fixture(page: Page) {
  await page.setViewportSize({ width: 1586, height: 992 })
  await loginAsAdmin(page); await csrf(page)
  const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
  const me = await json(await page.request.get('/api/v1/auth/me'))
  const jurisdictions = await json(await page.request.get('/api/v1/jurisdictions?limit=1000'))
  const jurisdiction = jurisdictions.items.find((item: { code: string }) => item.code === 'example')
  const contributor = await json(await page.request.post('/api/v1/users', { data: { email: `journey-${suffix}@example.com`, password: e2eAdminPassword, full_name: `Journey contributor ${suffix}`, role: 'contributor' } }))
  const template = await json(await page.request.post('/api/v1/preparation/templates', { data: { name: `Journey ownership ${suffix}`, kind: 'licence_application', fields: [{ key: 'ownership', label: 'Describe the ownership structure.', help_text: 'Identify the supporting documents and beneficial owners.', type: 'multiline', required: true, section: 'Ownership' }, { key: 'directors', label: 'Name the directors.', type: 'multiline', required: true, section: 'Governance' }] } }))
  let pack = await json(await page.request.post('/api/v1/applications', { data: { name: `Journey licence ${suffix}`, jurisdiction_id: jurisdiction.id, scope: 'annex_only', visibility: 'organisation', owner_id: me.id } }))
  pack = await json(await page.request.post(`/api/v1/applications/${pack.id}/components`, { data: { expected_revision: pack.revision, name: 'Ownership declaration', kind: 'annex', template_id: template.id, owner_id: contributor.id, required: true, included: true } }))
  let form = await json(await page.request.get(`/api/v1/preparation/cases/${pack.components[0].case_id}`))
  form = await json(await page.request.patch(`/api/v1/preparation/cases/${form.id}`, { data: { expected_revision: form.revision, owner_id: contributor.id, reviewer_id: me.id } }))
  for (const key of ['ownership', 'directors']) form = await json(await page.request.put(`/api/v1/preparation/cases/${form.id}/responses/${key}`, { data: { expected_revision: form.revision, value: key === 'ownership' ? 'Initial ownership answer.' : 'Two appointed directors.', evidence_ids: [], not_applicable_reason: null } }))
  form = await json(await page.request.post(`/api/v1/preparation/cases/${form.id}/responses/ownership/accept`, { data: { expected_revision: form.revision } }))
  return { pack, form, contributor, jurisdiction, url: `/licence-applications?application=${pack.id}&case=${form.id}&field=ownership` }
}
async function contributorPage(browser: Browser, email: string, jurisdictionId: string) {
  const context = await browser.newContext({ baseURL: 'http://127.0.0.1:15173', viewport: { width: 1586, height: 992 } })
  const page = await context.newPage()
  await page.goto('/login'); await page.locator('input[type=email]').fill(email); await page.locator('input[type=password]').fill(e2eAdminPassword!); await page.locator('button[type=submit]').click(); await page.waitForURL('/')
  await page.getByLabel('Jurisdiction selector').selectOption(jurisdictionId); await csrf(page)
  return { context, page }
}
const readForm = async (page: Page, id: string) => json(await page.request.get(`/api/v1/preparation/cases/${id}`))
const answer = (form: { responses: Array<{ field_key: string; value: unknown; evidence_ids: string[]; accepted_at: string | null; review_status?: string; feedback?: Array<{ comment: string; resolved_at: string | null }> }> }) => form.responses.find(item => item.field_key === 'ownership')!

test('contributor evidence replacement, return feedback and re-review persist end to end', async ({ page, browser }, info) => {
  const f = await fixture(page)
  const contributor = await contributorPage(browser, f.contributor.email, f.jurisdiction.id)
  try {
    const work = contributor.page
    await work.goto(f.url)
    const question = work.getByRole('article', { name: 'Describe the ownership structure.' })
    await expect(question.getByText('Accepted', { exact: true })).toBeVisible()
    await question.getByRole('textbox', { name: 'Describe the ownership structure.' }).fill('The company is owned by two founders. Supporting chart attached.')
    await expect.poll(async () => answer(await readForm(work, f.form.id)).value).toContain('two founders')
    expect(answer(await readForm(work, f.form.id)).accepted_at).toBeNull()
    await question.getByLabel('Upload evidence for this answer').setInputFiles('e2e/fixtures/test.pdf')
    const uploadResponse = work.waitForResponse(response => response.url().endsWith('/preparation/evidence/upload') && response.request().method() === 'POST')
    await question.getByRole('button', { name: 'Upload and attach', exact: true }).click()
    await json(await uploadResponse)
    await expect(question.getByText(/test.pdf attached to this answer/)).toBeVisible()
    const previous = answer(await readForm(work, f.form.id)).evidence_ids[0]
    expect(previous).toBeTruthy()
    await page.goto(`/answer-review?case_filter=${f.form.id}&case=${f.form.id}&field=ownership`)
    await expect(page.getByRole('heading', { name: 'Describe the ownership structure.' })).toBeVisible()
    await page.getByRole('button', { name: 'Accept answer & next' }).click()
    await expect.poll(async () => answer(await readForm(page, f.form.id)).accepted_at).toBeTruthy()
    await work.reload()
    await question.getByLabel('Attachment action').selectOption(previous)
    await question.getByLabel('Upload evidence for this answer').setInputFiles({ name: 'signed-group-chart.pdf', mimeType: 'application/pdf', buffer: pdfBytes })
    await question.getByRole('button', { name: 'Upload replacement and attach' }).click()
    await expect(question.getByText(/signed-group-chart.pdf attached to this answer/)).toBeVisible()
    await expect(question.getByRole('button', { name: 'Remove signed-group-chart.pdf' })).toBeVisible()
    await capture(work, info.outputPath('desktop-evidence-replacement-saved.png'))
    const replaced = answer(await readForm(work, f.form.id))
    expect(replaced.evidence_ids).toHaveLength(1); expect(replaced.evidence_ids[0]).not.toBe(previous); expect(replaced.accepted_at).toBeNull()
    await page.goto(`/answer-review?case_filter=${f.form.id}&case=${f.form.id}&field=ownership`)
    await expect(page.getByTitle('Evidence preview: signed-group-chart.pdf')).toBeVisible()
    await expect(page.getByTitle('Evidence preview: signed-group-chart.pdf')).toHaveAttribute('src', /^blob:/)
    await page.waitForLoadState('networkidle')
    await capture(page, info.outputPath('desktop-answer-review-pdf-evidence.png'))
    await page.getByRole('button', { name: 'Return for changes', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Send back for changes' })).toBeDisabled()
    await page.getByRole('textbox', { name: 'Comment for the contributor' }).fill('Identify each beneficial owner by name.')
    await page.getByRole('button', { name: 'Send back for changes' }).click()
    await expect.poll(async () => answer(await readForm(page, f.form.id)).review_status).toBe('changes_requested')
    await work.reload()
    await expect(work.getByText('Identify each beneficial owner by name.', { exact: true })).toBeVisible()
    await question.getByRole('textbox', { name: 'Describe the ownership structure.' }).fill('The beneficial owners are Alex Example and Jamie Example, each holding 50%.')
    await expect.poll(async () => answer(await readForm(work, f.form.id)).review_status).toBe('pending_review')
    expect(answer(await readForm(work, f.form.id)).feedback?.some(item => !item.resolved_at)).toBeTruthy()
    await page.goto(`/answer-review?case_filter=${f.form.id}&case=${f.form.id}&field=ownership`)
    await expect(page.getByText('Identify each beneficial owner by name.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Accept answer & next' }).click()
    await expect.poll(async () => answer(await readForm(page, f.form.id)).accepted_at).toBeTruthy()
    expect(answer(await readForm(page, f.form.id)).feedback?.every(item => item.resolved_at)).toBeTruthy()
    await expect(page.getByRole('heading', { name: 'Name the directors.' })).toBeVisible()
    const history = await json(await page.request.get(`/api/v1/preparation/cases/${f.form.id}/responses/ownership/history`))
    expect(JSON.stringify(history)).toContain(previous)
  } finally { await contributor.context.close() }
})

test('failed upload and failed attachment preserve current evidence and attachment retry does not upload twice', async ({ page }, info) => {
  const f = await fixture(page)
  await page.goto(f.url)
  const question = page.getByRole('article', { name: 'Describe the ownership structure.' })
  await question.getByLabel('Upload evidence for this answer').setInputFiles('e2e/fixtures/test.pdf')
  await question.getByRole('button', { name: 'Upload and attach', exact: true }).click()
  await expect(question.getByText(/test.pdf attached to this answer/)).toBeVisible()
  const oldId = answer(await readForm(page, f.form.id)).evidence_ids[0]
  await question.getByLabel('Attachment action').selectOption(oldId)
  await question.getByLabel('Upload evidence for this answer').setInputFiles({ name: 'replacement.pdf', mimeType: 'application/pdf', buffer: pdfBytes })
  await page.route('**/api/v1/preparation/evidence/upload', route => route.abort('failed'), { times: 1 })
  await question.getByRole('button', { name: 'Upload replacement and attach' }).click()
  await expect(question.getByRole('button', { name: 'Retry upload' })).toBeVisible()
  expect(answer(await readForm(page, f.form.id)).evidence_ids).toEqual([oldId])
  await page.setViewportSize({ width: 390, height: 844 })
  await capture(page, info.outputPath('mobile-upload-interrupted.png'))
  let uploads = 0
  page.on('request', request => { if (request.url().endsWith('/preparation/evidence/upload')) uploads += 1 })
  await page.route(`**/api/v1/preparation/cases/${f.form.id}/responses/ownership`, async route => { if (route.request().method() === 'PUT') await route.fulfill({ status: 503, json: { detail: 'Synthetic attachment failure' } }); else await route.continue() }, { times: 1 })
  await question.getByRole('button', { name: 'Retry upload' }).click()
  await expect(question.getByText(/file uploaded, but was not attached/)).toBeVisible()
  expect(answer(await readForm(page, f.form.id)).evidence_ids).toEqual([oldId])
  await page.getByRole('button', { name: /^(Resume editing|Retry saving)$/ }).click()
  await question.getByRole('button', { name: 'Retry attaching uploaded file' }).click()
  await expect(question.getByText(/replacement.pdf attached to this answer/)).toBeVisible()
  expect(uploads).toBe(1)
  expect(answer(await readForm(page, f.form.id)).evidence_ids).not.toContain(oldId)
})

test('mobile focused navigation, drawer and concurrent-edit comparison retain drafts until explicit save', async ({ page }, info) => {
  const f = await fixture(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(f.url)
  await page.getByRole('button', { name: /Pack contents ·/ }).click()
  await expect(page.getByRole('dialog', { name: 'Pack contents' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Pack contents' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Next question', exact: true }).first().click()
  await expect(page.getByRole('textbox', { name: 'Name the directors.' })).toBeVisible()
  await page.getByRole('button', { name: 'Previous question', exact: true }).click()
  const local = page.getByRole('textbox', { name: 'Describe the ownership structure.' })
  const latest = await readForm(page, f.form.id)
  await json(await page.request.put(`/api/v1/preparation/cases/${f.form.id}/responses/ownership`, { data: { expected_revision: latest.revision, value: 'A newer answer from another editor.', not_applicable_reason: null, evidence_ids: [] } }))
  await local.fill('My unsaved ownership draft.')
  await expect(page.getByText('This form changed while you were editing.', { exact: true })).toBeVisible()
  await expect(local).toHaveValue('My unsaved ownership draft.')
  await expect(page.getByText('A newer answer from another editor.', { exact: true })).toBeVisible()
  await capture(page, info.outputPath('mobile-concurrent-edit-comparison.png'))
  await page.getByRole('button', { name: 'Review and combine changes', exact: true }).click()
  await local.fill('Combined ownership answer reviewed against the newer answer.')
  await expect.poll(async () => answer(await readForm(page, f.form.id)).value).toBe('A newer answer from another editor.')
  await page.getByRole('button', { name: 'Save combined answer', exact: true }).click()
  await expect.poll(async () => answer(await readForm(page, f.form.id)).value).toBe('Combined ownership answer reviewed against the newer answer.')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('attachment controls cannot mutate the answer while an upload is held in flight', async ({ page }) => {
  const f = await fixture(page)
  await page.goto(f.url)
  const question = page.getByRole('article', { name: 'Describe the ownership structure.' })
  await question.getByLabel('Upload evidence for this answer').setInputFiles('e2e/fixtures/test.pdf')
  await question.getByRole('button', { name: 'Upload and attach', exact: true }).click()
  await expect(question.getByText(/test.pdf attached to this answer/)).toBeVisible()
  const before = answer(await readForm(page, f.form.id)).evidence_ids
  let release!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/v1/preparation/evidence/upload', async route => { await held; await route.continue() }, { times: 1 })
  await question.getByLabel('Upload evidence for this answer').setInputFiles({ name: 'additional-record.pdf', mimeType: 'application/pdf', buffer: pdfBytes })
  await question.getByRole('button', { name: 'Upload and attach', exact: true }).click()
  await expect(question.getByRole('button', { name: 'Remove test.pdf' })).toBeDisabled()
  await expect(question.getByRole('button', { name: 'Add evidence', exact: true })).toBeDisabled()
  const remote = await readForm(page, f.form.id)
  expect(answer(remote).evidence_ids).toEqual(before)
  await json(await page.request.put(`/api/v1/preparation/cases/${f.form.id}/responses/ownership`, { data: { expected_revision: remote.revision, value: 'Another editor changed the answer during upload.', evidence_ids: before, not_applicable_reason: null } }))
  release()
  await expect(question.getByText(/file uploaded, but was not attached/)).toBeVisible()
  await page.getByRole('button', { name: 'Use latest form for attachment retry' }).click()
  await question.getByRole('button', { name: 'Retry attaching uploaded file' }).click()
  await expect(question.getByText(/additional-record.pdf attached to this answer/)).toBeVisible()
  const saved = answer(await readForm(page, f.form.id))
  expect(saved.evidence_ids).toHaveLength(2); expect(saved.evidence_ids).toContain(before[0])
  expect(saved.value).toBe('Another editor changed the answer during upload.')
})

test('a conflict refresh removes a detached evidence preview before latest answer acceptance', async ({ page }) => {
  const f = await fixture(page)
  const upload = async (name: string) => json(await page.request.post('/api/v1/preparation/evidence/upload', { multipart: { title: name, case_id: f.form.id, file: { name, mimeType: 'application/pdf', buffer: pdfBytes } } }))
  const a = await upload('still-current-A.pdf'), b = await upload('replaced-B.pdf'), c = await upload('replacement-C.pdf')
  let current = await readForm(page, f.form.id)
  current = await json(await page.request.put(`/api/v1/preparation/cases/${f.form.id}/responses/ownership`, { data: { expected_revision: current.revision, value: 'Answer with two attachments.', evidence_ids: [a.id, b.id], not_applicable_reason: null } }))
  await page.goto(`/answer-review?case_filter=${f.form.id}&case=${f.form.id}&field=ownership`)
  const selectedResponse = answer(current)
  const bIndex = selectedResponse.evidence_ids.indexOf(b.id)
  await page.getByLabel('Preview attachment').selectOption(b.id)
  expect(bIndex).toBeGreaterThanOrEqual(0)
  await expect(page.getByRole('region', { name: 'Selected evidence preview' }).getByText('replaced-B.pdf')).toBeVisible()
  await json(await page.request.put(`/api/v1/preparation/cases/${f.form.id}/responses/ownership`, { data: { expected_revision: current.revision, value: 'Answer with current replacement.', evidence_ids: [a.id, c.id], not_applicable_reason: null } }))
  await page.getByRole('button', { name: 'Accept answer & next' }).click()
  await expect(page.getByRole('button', { name: 'I have reviewed the latest answer' })).toBeEnabled()
  await expect(page.getByRole('region', { name: 'Selected evidence preview' }).getByText('replaced-B.pdf')).not.toBeVisible()
  await page.getByLabel('Preview attachment').selectOption(c.id)
  await expect(page.getByRole('region', { name: 'Selected evidence preview' }).getByText('replacement-C.pdf')).toBeVisible()
  await page.getByRole('button', { name: 'I have reviewed the latest answer' }).click()
  await page.getByRole('button', { name: 'Accept answer & next' }).click()
  await expect.poll(async () => answer(await readForm(page, f.form.id)).accepted_at).toBeTruthy()
  expect(answer(await readForm(page, f.form.id)).evidence_ids.sort()).toEqual([a.id, c.id].sort())
})
