import { test, expect } from '@playwright/test'
import { loginAsAdmin } from './testCredentials'

test('assessment controls remain readable and usable across themes and mobile', async ({ page }, info) => {
  await loginAsAdmin(page)
  // This checks the working layout after the optional introduction is dismissed.
  // First-use invitation and its mobile layout have separate product-tour coverage.
  await page.getByRole('region', { name: 'Product tour invitation' }).getByRole('button', { name: 'Not now', exact: true }).click()
  const token = (await page.context().cookies()).find(cookie => cookie.name === 'access_token')!.value
  const headers = { Authorization: `Bearer ${token}` }
  const jurisdictions = await (await page.request.get('/api/v1/jurisdictions?limit=1000', { headers })).json()
  const jurisdiction = jurisdictions.items.find((item: { code: string }) => item.code === 'example')
  const sets = await (await page.request.get(`/api/v1/requirements/sets?jurisdiction_id=${jurisdiction.id}&limit=1000`, { headers })).json()
  const source = sets.items.find((item: { name: string }) => item.name === 'E2E Document')
  const created = await page.request.post('/api/v1/review-cycles', { headers, data: { name: `Readability check ${Date.now()}`, jurisdiction_id: jurisdiction.id, document_ids: [source.document_id], scope: 'documents' } })
  expect(created.status()).toBe(201)
  const cycle = await created.json()
  for (const theme of ['light', 'dark']) {
    await page.evaluate(value => localStorage.setItem('cap:theme', value), theme)
    await page.goto(`/review-cycles/${cycle.id}`)
    await expect(page.getByLabel('Evidence for REQ-001', { exact: true })).toBeVisible()
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    const ratios = await page.evaluate(() => {
      const root = getComputedStyle(document.documentElement)
      const rgb = (name: string) => root.getPropertyValue(`--${name}`).trim().split(/\s+/).map(Number)
      const luminance = (values: number[]) => values.map(x => x / 255).map(x => x <= .04045 ? x / 12.92 : ((x + .055) / 1.055) ** 2.4).reduce((sum, x, index) => sum + x * [.2126,.7152,.0722][index], 0)
      const ratio = (foreground: number[], background: number[]) => { const values = [luminance(foreground), luminance(background)].sort((a,b)=>b-a); return (values[0]+.05)/(values[1]+.05) }
      return ['ink','muted','faint'].flatMap(text => ['canvas','surface','subtle'].map(surface => ({ text, surface, value: ratio(rgb(text),rgb(surface)) })))
    })
    for (const check of ratios) expect(check.value, `${theme} ${check.text} on ${check.surface}`).toBeGreaterThanOrEqual(4.5)
    const next = page.getByRole('button', { name: 'Next needing attention', exact: true })
    const colours = await next.evaluate(el => { const css=getComputedStyle(el); return { text:css.color,background:css.backgroundColor } })
    expect(colours.text).not.toBe(colours.background)
    for (const button of await page.getByRole('button', { name: 'Assign to me', exact: true }).all()) {
      if (!(await button.isVisible())) continue
      const box=await button.locator('svg').boundingBox()
      expect(box!.width).toBeGreaterThanOrEqual(16)
    }
    await page.screenshot({ path: info.outputPath(`assessment-${theme}-desktop.png`), fullPage:true })
    await page.setViewportSize({width:390,height:844})
    await expect(page.getByRole('button',{name:'Filters and view options',exact:true})).toBeVisible()
    await expect(page.locator('#assessment-tools')).toBeHidden()
    await expect(page.locator('.assessment-summary')).not.toHaveAttribute('open')
    expect((await page.locator('[id^=review-item-]').first().boundingBox())!.y).toBeLessThan(844)
    await expect(page.getByLabel('Evidence for REQ-001', { exact:true })).toBeVisible()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await page.screenshot({path:info.outputPath(`assessment-${theme}-mobile.png`),fullPage:true,animations:'disabled'})
    await page.getByRole('button',{name:'Filters and view options',exact:true}).click()
    await expect(page.locator('#assessment-tools')).toBeVisible()
    await page.getByRole('button',{name:'Hide filters and view options',exact:true}).click()
    await page.reload()
    await expect(page.locator('html')).toHaveAttribute('data-theme',theme)
    await page.setViewportSize({width:1440,height:1000})
  }
})

test('resource collections preserve drafts through the Resources navigation', async ({page}) => {
  await page.setViewportSize({width:1440,height:1000})
  await loginAsAdmin(page)
  await page.goto('/library?section=evidence')
  await expect(page.getByRole('heading',{name:'Evidence',exact:true,level:1})).toBeVisible()
  await expect(page.getByRole('navigation',{name:'Resource collections'})).toHaveCount(0)
  await page.getByRole('button',{name:'Resources',exact:true}).click()
  await expect(page.locator('#resource-navigation').getByRole('link',{name:'Evidence',exact:true})).toHaveAttribute('aria-current','page')
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Add evidence',exact:true}).click()
  await page.getByLabel('Title',{exact:true}).fill('Draft evidence note')
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Draft evidence note')
  await page.getByRole('button',{name:'Back to evidence · Draft kept',exact:true}).click()
  await expect(page.getByLabel('Title',{exact:true})).toBeHidden()
  await page.getByRole('button',{name:'Resume evidence draft',exact:true}).click()
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Draft evidence note')
  await page.getByRole('button',{name:'Resources',exact:true}).click()
  await page.locator('#resource-navigation').getByRole('link',{name:'Form templates',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Changes are not saved yet'})).toBeVisible()
  await page.getByRole('button',{name:'Leave with unsaved changes',exact:true}).click()
  await page.getByRole('button',{name:'New blank form',exact:true}).click()
  await page.getByLabel('Blank form name',{exact:true}).fill('Draft template')
  await expect(page.getByLabel('Blank form name',{exact:true})).toHaveValue('Draft template')
  await page.getByRole('button',{name:'Back to templates · Draft kept',exact:true}).click()
  await expect(page.getByLabel('Blank form name',{exact:true})).toBeHidden()
  await page.getByRole('button',{name:'Resume draft',exact:true}).click()
  await expect(page.getByLabel('Blank form name',{exact:true})).toHaveValue('Draft template')
  await expect(page.getByRole('button',{name:'Resources',exact:true})).toHaveAttribute('aria-expanded','false')
  await page.getByLabel('Blank form name',{exact:true}).fill('')
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await expect(page.getByRole('button',{name:'Resources',exact:true})).toHaveAttribute('aria-expanded','false')
})


test('horizontal shell keeps navigation, search, themes and mobile focus accessible', async ({page}, info) => {
  await page.setViewportSize({width:1440,height:1000})
  await loginAsAdmin(page)
  await page.goto('/account')
  const nav=page.getByRole('navigation',{name:'Primary navigation',exact:true})
  for (const name of ['Overview','Licence Applications','Certifications','Change Management']) {
    await expect(nav.getByRole('link',{name,exact:true})).toBeVisible()
  }
  expect((await page.locator('.app-topbar').boundingBox())!.height).toBe(60)
  await expect(page.getByTestId('mobile-nav-toggle')).toBeHidden()
  const resources=page.getByRole('button',{name:'Resources',exact:true})
  await resources.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('#resource-navigation').getByRole('link',{name:'Requirements',exact:true})).toBeFocused()
  for (const name of ['Form templates','Evidence','Existing forms','Teams','Reports','Guide & FAQ','Change notes','Settings','Jurisdictions','User Management']) {
    await expect(page.locator('#resource-navigation').getByRole('link',{name,exact:true})).toBeVisible()
  }
  await page.keyboard.press('Escape')
  await expect(resources).toBeFocused()
  await expect(resources).toHaveAttribute('aria-expanded','false')
  await page.getByRole('button',{name:'Find a page',exact:true}).click()
  await page.getByRole('combobox',{name:'Search pages',exact:true}).fill('My account')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/account$/)
  await expect(page.getByRole('dialog',{name:'Go to a page',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Profile options',exact:true}).click()
  await expect(page.getByRole('link',{name:'Account settings',exact:true})).toBeVisible()
  await expect(page.getByRole('link',{name:'Notification settings',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Use dark theme',exact:true}).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.keyboard.press('Escape')
  // Theme help is the top keyboard layer; dismiss the profile after its tooltip.
  if (await page.getByRole('button',{name:'Profile options',exact:true}).getAttribute('aria-expanded') === 'true') await page.keyboard.press('Escape')
  await page.screenshot({path:info.outputPath('shell-dark-desktop.png'),fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Profile options',exact:true}).click()
  await page.getByRole('button',{name:'Use light theme',exact:true}).click()
  await page.keyboard.press('Escape')
  if (await page.getByRole('button',{name:'Profile options',exact:true}).getAttribute('aria-expanded') === 'true') await page.keyboard.press('Escape')
  await page.screenshot({path:info.outputPath('shell-light-desktop.png'),fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  const toggle=page.getByTestId('mobile-nav-toggle')
  await toggle.click()
  const drawer=page.getByRole('dialog',{name:'Navigation',exact:true})
  await expect(drawer).toBeVisible()
  await expect(drawer.getByRole('button',{name:'Close',exact:true})).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(drawer.getByRole('link',{name:'My account',exact:true})).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(drawer.getByRole('button',{name:'Close',exact:true})).toBeFocused()
  for (const name of ['Licence Applications','Reports','Evidence','User Management']) {
    await expect(drawer.getByRole('link',{name,exact:true})).toHaveCount(1)
  }
  await drawer.getByRole('navigation',{name:'Primary navigation',exact:true}).evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({path:info.outputPath('shell-mobile-navigation.png'),fullPage:true,animations:'disabled'})
  await page.keyboard.press('Escape')
  await expect(drawer).toHaveCount(0)
  await expect(toggle).toBeFocused()
  await page.getByRole('button',{name:'Find a page',exact:true}).click()
  await expect(page.getByRole('combobox',{name:'Search pages',exact:true})).toBeFocused()
  await page.keyboard.press('Escape')
  await page.screenshot({path:info.outputPath('shell-light-mobile.png'),fullPage:true,animations:'disabled'})
})
